[theme]
primaryColor = "#ff69b4"  # Pink for buttons
backgroundColor = "#fff0f5"  # Light pink background
secondaryBackgroundColor = "#ffe4e1"  # Misty rose for sidebar
textColor = "#5a5a5a"  # Dark gray text
font = "sans serif"
